# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yeo < Formula
  desc "Yeo! is a tiny backup utility for PostgreSQL databases."
  homepage "https://github.com/jjcfrancisco/yeo"
  version "0.4.4"
  license "Apache License 2.0"

  depends_on "libpq"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/jjcfrancisco/yeo/releases/download/v0.4.4/yeo_Darwin_arm64.tar.gz"
    sha256 "a4f3a24de84ccf21f932b8813364d366342db486d496e364800e0c471573a2b7"

    def install
      bin.install "yeo"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/jjcfrancisco/yeo/releases/download/v0.4.4/yeo_Darwin_x86_64.tar.gz"
    sha256 "6116b91a27fa7d9e9ed6913b94e1bcc7375b87fceb0e32c346e5923a8ac45cf9"

    def install
      bin.install "yeo"
    end
  end
end
