# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yeo < Formula
  desc "Yeo! is a tiny backup utility for PostgreSQL databases."
  homepage "https://github.com/jjcfrancisco/yeo"
  version "0.4.5"
  license "Apache License 2.0"

  depends_on "libpq"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/jjcfrancisco/yeo/releases/download/v0.4.5/yeo_Darwin_arm64.tar.gz"
    sha256 "4b951e2e3d1fcea5dcc836d60c156db3fd2bdc281abaeff003bd7f9f746a10e6"

    def install
      bin.install "yeo"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/jjcfrancisco/yeo/releases/download/v0.4.5/yeo_Darwin_x86_64.tar.gz"
    sha256 "8325f2ebbf50eb82ef48018f269f6384abcb56e07c6aba2f03e9739793a5f18b"

    def install
      bin.install "yeo"
    end
  end
end
